### ISSUE TITLE
Temporary contents are left

### ISSUE THREAD

**Issue by jmfernandez** [Acivico/WfExS-backend#1]
In method starting at https://github.com/Acivico/WfExS-backend/blob/16bdcd01002cd2bbd7c10878576df4ca9fa54001/wfexs_backend/fetchers/s3.py#L13 the downloaded contents are saved to their own names, and later copied to the definitive ones. The problem is that the initial copy is also kept there.

Possible fixes are:

* Moving instead of copying (in next block):
  https://github.com/Acivico/WfExS-backend/blob/16bdcd01002cd2bbd7c10878576df4ca9fa54001/wfexs_backend/fetchers/s3.py#L73-L80
* Using the name directly

**Comment by Acivico** [comment]
Commit hash: 00eec8abd4b2ac7305672923ffbcfaf25bcf08a3

Solved issue:
It has been changed so that instead of copying it moves

    if os.path.isdir(local_path):
        shutil.move(local_path, cachedFilename)
        kind = ContentKind.Directory
    elif os.path.isfile(local_path):
        shutil.move(local_path, cachedFilename)
        kind = ContentKind.File
    else:
        raise WFException("Local path {} is neither a file nor a directory".format(local_path))

**Comment by jmfernandez** [comment]
Thanks!
